# Константы и начальные настройки
MAX_LEVEL = 10
INITIAL_BALANCE = 200
EXPERIENCE_THRESHOLD = 100
COLONY_COUNT = 10
SIMULATION_TIME = 250
ITERATIONS_PER_CYCLE = 10
AUCTION_INTERVAL = 50
EVENT_INTERVAL = 15
MAX_BET = 0.75
LOG_FILE = "simulation_log.txt"